version: '3'
services:
  datadog:
    image: datadog/agent:latest
    env_file:
     - .env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
     - "8125:8125/udp"
